export const AUDIT_LOG_EVENT_TYPES = [
  "AUTHORIZE_RECEIVED",
  "PROXY_REDIRECT_OUT",
  "PROXY_CALLBACK_SUCCESS",
  "PROXY_CALLBACK_ERROR",
  "PROXY_CODE_ISSUED",
  "TOKEN_AUTHCODE_RECEIVED",
  "TOKEN_AUTHCODE_COMPLETED",
  "TOKEN_REFRESH_RECEIVED",
  "TOKEN_REFRESH_COMPLETED",
  "CONFIG_CHANGED",
  "SECURITY_VIOLATION",
] as const;

export type AuditLogEventType = (typeof AUDIT_LOG_EVENT_TYPES)[number];

export const AUDIT_LOG_SEVERITIES = ["INFO", "WARN", "ERROR"] as const;

export type AuditLogSeverity = (typeof AUDIT_LOG_SEVERITIES)[number];
